logging:
  level:
    root: info
spring:
  application:
    name: InMemoryCache2K
  config:
    import: classpath:config/inmemorycache.yml,classpath:config/inmemorycache.yml

management:
  endpoints:
    web:
      exposure:
        include: "*"
